# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkdevice',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='server',
            name='asset',
        ),
        migrations.AddField(
            model_name='asset',
            name='network',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='repository.Asset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='server',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='repository.Server'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='标签'),
        ),
    ]
