# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20170705_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='network',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='server',
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='asset',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='repository.Asset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='asset',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='repository.Asset'),
            preserve_default=False,
        ),
    ]
